### ISSUE TITLE
Getting error when running doRequest

### ISSUE THREAD

**Issue by paulrostorp** [dgraph-io/dgraph-js#72]
Version 2.0.1:
Hi I am getting the following error when running any code from the readme...
```(node:85377) UnhandledPromiseRejectionWarning: TypeError: jspb.Message.getBooleanFieldWithDefault is not a function

(node:58011) UnhandledPromiseRejectionWarning: TypeError: jspb.Message.getBooleanFieldWithDefault is not a function
    at Function.proto.api.Request.toObject (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/generated/api_pb.js:368:28)
    at proto.api.Request.toObject (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/generated/api_pb.js:350:28)
    at Object.stringifyMessage (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/lib/util.js:52:31)
    at Txn.<anonymous> (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/lib/txn.js:132:64)
    at step (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/lib/txn.js:43:23)
    at Object.next (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/lib/txn.js:24:53)
    at /Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/lib/txn.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/lib/txn.js:14:12)
    at Txn.doRequest (/Users/paulrostorp/Documents/Apps/kickoff-project/kickoff-api/node_modules/dgraph-js/lib/txn.js:112:16)
```
any suggestions ?

**Comment by prashant-shahi** [comment]
@paulrostorp May I know which Dgraph version are you running?

**Comment by paulrostorp** [comment]
1.1.0
Checked in the logs of each container, all showing v1.1.0, and running without problems. Running new upserts from ratel dashboard works as well.
Getting this error in the js client when doing anything more than initializing the client...
Also tried running with play.dgraph.io as the db, but same error occurs.

**Comment by prashant-shahi** [comment]
That shouldn't be the case.

It would be really helpful if you could share the `docker-compose` file (if any) and the minimum code snippet that causes the error?

**Comment by paulrostorp** [comment]
My docker-compose:
```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - /data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: always
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - /data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: always
    command: dgraph alpha --my=server:7080 --lru_mb=4100 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
    restart: always
```

attempted code: 
```
const dgraph = require("dgraph-js");
const grpc = require("grpc");

const clientStub = new dgraph.DgraphClientStub(
    process.env.DGRAPH_HOST + ":9080",
    grpc.credentials.createInsecure(),
  );
const dgraphClient = new dgraph.DgraphClient(clientStub);
dgraphClient.setDebugMode(true);
console.log('Dgraph host: ', process.env.DGRAPH_HOST);

main = async () => {
    const query = `query all($a: string) {
        all(func: eq(name, $a))
        {
          name
        }
      }`;
      const vars = { $a: "Alice" };
      const res = await dgraphClient.newTxn().queryWithVars(query, vars);
      const ppl = res.getJson();
      
      // Print results.
      console.log(`Number of people named "Alice": ${ppl.all.length}`);
}
main();
```

But any code from the readme or examples triggers the same error. I have performed a "drop all" on my db as well.
